version: '3.9'
services:
  prefect-server:
    image: prefecthq/prefect:3.0.0rc14-python3.11
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - "4200:4200"
    networks:
      - prefect-network
networks:
  prefect-network:
    driver: bridge