version: '3.9'
services:
  prefect-server:
    image: prefecthq/prefect:3.0.0rc14-python3.11
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - "4200:4200"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    networks:
      - prefect-network

  prefect-worker:
    build: .
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    networks:
      - prefect-network
    command: ["python", "hello.py"]

networks:
  prefect-network:
    driver: bridge